### ISSUE TITLE
Run interactive fails.

### ISSUE THREAD

**Issue by TimeLordRaps** [Shalev-Lifshitz/STEVE-1#1]
Seems to be an import issue with whatever t2b is. I couldn't find anything on this library, so I assume it's an artifact of refactoring, and missing changes to run_interactive.py. Upon looking at run_agent.py compared to run_interactive.py t2b seems like it should be steve1, but then when I change them to steve1. I get this error:
ModuleNotFoundError: No module named 'steve1.utils.text_overlay_utils'. May you please add this file if it is intended to be in the repo?

**Comment by Shalev-Lifshitz** [comment]
Thanks for letting me know. Just pushed a fix!
