### ISSUE TITLE
Gym version 0.19 or 0.21 (or newer)?

### ISSUE THREAD

**Issue by karsmars** [Shalev-Lifshitz/STEVE-1#11]
Some of the install requirements (like MineDojo) specifically require gym version 0.21.0, while the VPT step changes this to gym 0.19. Is there a way to use both, or should we install only version 0.21? Or am I the only one with this issue?

**Comment by Shalev-Lifshitz** [comment]
Hi there, thanks for asking this question. You should use the gym version required by VPT as we don't use the parts of MineDojo that require gym. If you install in the order specified in the README it should work correctly. But I'll add a a sentence to the README making this clear.
