### ISSUE TITLE
the original dataset

### ISSUE THREAD

**Issue by evelinehong** [Shalev-Lifshitz/STEVE-1#14]
Hi, do you provide the 54M dataset?

**Comment by Shalev-Lifshitz** [comment]
Hi there, most of the dataset is sourced from the dataset used to train VPT, which can be found at their [repo](https://github.com/openai/Video-Pre-Training). Unfortunately, the rest of the dataset (~15M frames) is not publicly available (it is difficult to host such a large amount of data). See the STEVE-1 [paper](https://arxiv.org/abs/2306.00937) for more details about the dataset.
