### ISSUE TITLE
How did you generate the goal embeddings for policy training?

### ISSUE THREAD

**Issue by motata** [Shalev-Lifshitz/STEVE-1#15]
Hi, thank you for the interesting work. After having checked the code, I'm curious about how you generated the goal embeddings for training the policy? How to align the goal embeddings with the embeddings generated by the prior?
Thank you.

**Comment by motata** [comment]
I figured it out. Thanks.

**Comment by Shalev-Lifshitz** [comment]
Great to hear! Let me know if you have any other questions.
