### ISSUE TITLE
Running in headless mode

### ISSUE THREAD

**Issue by elicassion** [Shalev-Lifshitz/STEVE-1#4]
Hi @Shalev-Lifshitz 

I think it's worth to note that commands need to be run with `xvfb-run` on a headless server.
It's also worth to note that `MINEDOJO_HEADLESS=1` does not come to effect since this repo directly uses MineRL to create environments.

Thanks for the great work!

**Comment by Shalev-Lifshitz** [comment]
Just added info on how to run headless in the README, thanks!

**Comment by artbelyaev0** [comment]
Hello! may be anyone can help with settings for running interactive mode on a headless machine ?

**Comment by Shalev-Lifshitz** [comment]
Hi there, unfortunately I don't think the interactive script provided can run on a headless machine. However, the script which generates the videos given text prompts can run headless, and so you can try adapting that code to your use case!
