### ISSUE TITLE
About the dataset used to train STEVE-1

### ISSUE THREAD

**Issue by dealexce** [Shalev-Lifshitz/STEVE-1#7]
Hi STEVE-1 team,

I'm trying to train the STEVE-1 from scratch with the scripts in this repo. When generating the datasets with `train/1_generate_dataset.sh`, I found that only 12 episode each with ~3-5k frames are loaded. However in the STEVE-1 paper, it was said that 54M frames are used to train the model.

I'm wondering if the script pulling the full or sufficient dataset to train the model, or I will need to pull the larger dataset from somewhere else?

Thank you.

**Comment by Shalev-Lifshitz** [comment]
Hi there, thanks for asking this question. The first 3 commands in the `1_generate_dataset.sh` file should download a bunch of episodes from the publicly available VPT dataset (should be more than 200Gb in total, so it takes quite a while to download). Did these commands work for you?

**Comment by dealexce** [comment]
> Hi there, thanks for asking this question. The first 3 commands in the `1_generate_dataset.sh` file should download a bunch of episodes from the publicly available VPT dataset (should be more than 200Gb in total, so it takes quite a while to download). Did these commands work for you?

Thank you for the reply. 

They work but only a few episodes are downloaded. After a further look I found that the `N_EPISODES_CONTRACTOR` in `1_generate_dataset.sh` defines how many episodes to download from each version of VPT dataset, and it is set to `5`. After set it to a much larger number, more episodes are downloaded as supposed. 

I hope I get this right, and maybe it could be set to a larger number by default in this repo, or has some comment on the parameters?

**Comment by Shalev-Lifshitz** [comment]
Happy to hear that it's working now! Good idea about the comment, I'll add it now.
