### ISSUE TITLE
I fixed MineRL error, but now I can't run run_agent/3_run_interactive_session.sh

### ISSUE THREAD

**Issue by tonymacx86PRO** [Shalev-Lifshitz/STEVE-1#9]
Error:
```
Traceback (most recent call last):
  File "/home/coder/STEVE-1/steve1/run_agent/run_interactive.py", line 9, in <module>
    from steve1.utils.mineclip_agent_env_utils import load_mineclip_agent_env
  File "/home/coder/STEVE-1/steve1/utils/mineclip_agent_env_utils.py", line 9, in <module>
    from steve1.mineclip_code.load_mineclip import load
  File "/home/coder/STEVE-1/steve1/mineclip_code/load_mineclip.py", line 2, in <module>
    from mineclip import MineCLIP
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/__init__.py", line 2, in <module>
    from .dense_reward import (
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/__init__.py", line 1, in <module>
    from .animal_zoo import AnimalZooDenseRewardWrapper, HuntCowDenseRewardEnv
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/animal_zoo/__init__.py", line 2, in <module>
    from .hunt_cow import HuntCowDenseRewardEnv
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/animal_zoo/hunt_cow.py", line 4, in <module>
    import minedojo
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/__init__.py", line 1, in <module>
    from .tasks import make
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/tasks/__init__.py", line 83, in <module>
    _ALL_TASKS_SPECS_UNFILLED = OmegaConf.load(_resource_file_path("tasks_specs.yaml"))
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/tasks/__init__.py", line 29, in _resource_file_path
    with importlib_resources.path("minedojo.tasks.description_files", fname) as p:
AttributeError: module 'importlib_resources' has no attribute 'path'
```

**Comment by tonymacx86PRO** [comment]
Maybe use this?
`pip install importlib_resources`

**Comment by tonymacx86PRO** [comment]
I reinstalled it and I have some problems with minedojo and gym
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
minedojo 0.1 requires gym==0.21.0, but you have gym 0.19.0 which is incompatible.
```

**Comment by tonymacx86PRO** [comment]
So I found that the problem is in that minedojo needs gym 0.21.0 but then MineRL can't work with that version but when I installing gym 0.19.0 then works not minedojo but MineRL, can anyone explain why it this?

**Comment by Shalev-Lifshitz** [comment]
Hey again, yeah you should use the gym version that is required by MineRL, not the one required by MineDojo (since the STEVE-1 code uses MineRL, not MineDojo). So you should install gym 0.19.0.

**Comment by tonymacx86PRO** [comment]
yes I used the 0.19.0 but the code doesn't run and gives this error and it is for minedojo (maybe)
```
Successfully installed gym-0.19.0
(steve) coder@TONY-PC:~/STEVE-1$ . run_agent/3_run_interactive_session.sh
Traceback (most recent call last):
  File "/home/coder/STEVE-1/steve1/run_agent/run_interactive.py", line 9, in <module>
    from steve1.utils.mineclip_agent_env_utils import load_mineclip_agent_env
  File "/home/coder/STEVE-1/steve1/utils/mineclip_agent_env_utils.py", line 9, in <module>
    from steve1.mineclip_code.load_mineclip import load
  File "/home/coder/STEVE-1/steve1/mineclip_code/load_mineclip.py", line 2, in <module>
    from mineclip import MineCLIP
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/__init__.py", line 2, in <module>
    from .dense_reward import (
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/__init__.py", line 1, in <module>
    from .animal_zoo import AnimalZooDenseRewardWrapper, HuntCowDenseRewardEnv
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/animal_zoo/__init__.py", line 2, in <module>
    from .hunt_cow import HuntCowDenseRewardEnv
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/mineclip/dense_reward/animal_zoo/hunt_cow.py", line 4, in <module>
    import minedojo
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/__init__.py", line 1, in <module>
    from .tasks import make
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/tasks/__init__.py", line 83, in <module>
    _ALL_TASKS_SPECS_UNFILLED = OmegaConf.load(_resource_file_path("tasks_specs.yaml"))
  File "/home/coder/anaconda3/envs/steve/lib/python3.10/site-packages/minedojo/tasks/__init__.py", line 29, in _resource_file_path
    with importlib_resources.path("minedojo.tasks.description_files", fname) as p:
AttributeError: module 'importlib_resources' has no attribute 'path'
```

**Comment by tonymacx86PRO** [comment]
(steve) coder@TONY-PC:~/STEVE-1$ pip install gym==0.19 gym3 attrs opencv-python
Requirement already satisfied: gym==0.19 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (0.19.0)
Requirement already satisfied: gym3 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (0.3.3)
Requirement already satisfied: attrs in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (23.1.0)
Requirement already satisfied: opencv-python in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (4.8.0.76)
Requirement already satisfied: numpy>=1.18.0 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from gym==0.19) (1.23.5)
Requirement already satisfied: cloudpickle<1.7.0,>=1.2.0 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from gym==0.19) (1.6.0)
Requirement already satisfied: cffi<2.0.0,>=1.13.0 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from gym3) (1.15.1)
Requirement already satisfied: imageio<3.0.0,>=2.6.0 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from gym3) (2.31.1)
Requirement already satisfied: imageio-ffmpeg<0.4.0,>=0.3.0 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from gym3) (0.3.0)
Requirement already satisfied: glfw<2.0.0,>=1.8.6 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from gym3) (1.12.0)
Requirement already satisfied: moderngl<6.0.0,>=5.5.4 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from gym3) (5.8.2)
Requirement already satisfied: pycparser in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from cffi<2.0.0,>=1.13.0->gym3) (2.21)
Requirement already satisfied: pillow>=8.3.2 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from imageio<3.0.0,>=2.6.0->gym3) (9.4.0)
Requirement already satisfied: glcontext<3,>=2.3.6 in /home/coder/anaconda3/envs/steve/lib/python3.10/site-packages (from moderngl<6.0.0,>=5.5.4->gym3) (2.4.0)

**Comment by tonymacx86PRO** [comment]
minedojo tries to use an attribute that doesn't exist

**Comment by tonymacx86PRO** [comment]
the hello world is working with gym 0.19.0 that I have currently.

**Comment by tonymacx86PRO** [comment]
![image](https://github.com/Shalev-Lifshitz/STEVE-1/assets/42518347/9f9ce5df-1b74-41b0-8bb1-c7ef4d32cd2a)
Working hello world agent with MineRL

**Comment by tonymacx86PRO** [comment]
You know what is happening? I idk

**Comment by Shalev-Lifshitz** [comment]
I see, it seems that you are encountering an error with MineDojo when trying to import MineCLIP.  I would recommend looking at the MineDojo forums (i.e., GitHub repo issues) or search online for people who are encountering a similar issue. Also, this might be because you are trying to run in WSL. Unfortunately, I'm not sure how to fix that since you are running with WSL and the issue is with the MineDojo library, not the STEVE-1 code.

**Comment by tonymacx86PRO** [comment]
So what can I do? I am on windows and I don't have too much space for linux and I don't like dual boot because I can like destroy maybe windows and lost all data

**Comment by tonymacx86PRO** [comment]
Or maybe wait colab?

**Comment by tonymacx86PRO** [comment]
Also when colab will be released?

**Comment by Shalev-Lifshitz** [comment]
> So what can I do? I am on windows and I don't have too much space for linux and I don't like dual boot because I can like destroy maybe windows and lost all data

The error seems to be coming from the MineDojo/MineCLIP code, which is independent of the STEVE-1 code. So I would recommend reaching out to the MineDojo forums/developers or searching online to see if others encountered similar issues.

**Comment by Shalev-Lifshitz** [comment]
Regarding the collab, unfortunately we weren't able to get the environment working in collab. I'll go ahead and remove the collab coming soon from the Readme for now, thanks for raising this. Hopefully if another version of MineRL or MineDojo comes out in the future then we can try to set up the collab again, but for now it wasn't working for us.

**Comment by karsmars** [comment]
@tonymacx86PRO I'm also on WSL2 and the `importlib_resources` error is due to the `path` attribute being deprecated in current versions of the library. See this thread for a couple fixes:

- https://github.com/MineDojo/MineDojo/issues/94
